version: '3'

services:
  secretdev:
    image: enigmampc/secret-network-bootstrap-sw:latest
    stdin_open: true
    tty: true
    networks:
      - net
    hostname: secretdev
    volumes:
        - ".:/root/code"

  nginx:
    image: nginx:latest
    hostname: nginx
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - secretdev
    ports:
      - "1317:1317"
    networks:
      - net

networks:
    net:
